@echo off
cd /d "C:\Users\moro9\Desktop\Combo-Utility"
echo Switching to main branch...
git checkout main
echo Pulling latest changes...
git pull origin main
echo Merging Combo-Utility branch...
git merge Combo-Utility
echo Removing problematic files...
git rm --cached Combo-Website
git rm --cached "deployment add base path, router basename, and 404.html"
git rm --cached tatus
echo Committing cleanup...
git commit -m "Clean up repository: remove embedded repo and temp files"
echo Pushing to GitHub...
git push origin main
echo Done! Your website should be deployed now.
pause
